### ISSUE TITLE
Feature: Summary Stats

### ISSUE THREAD

**Issue by gracescharf** [iprado78/fullstack-iex-stock-ticker#1]
Component `<SummaryStats>` should display all the relevant statistics concerning an individual stock.

Dummy data to be used initially.

Requirements:
* Name of company 
* Highest price over 52 weeks
* Lowest price over 52 weeks
* Average volume over 30 days
* Change % over 30 days
* Employees

**Comment by dwalker11** [comment]
@gracescharf has fulfilled this request.
